FROM php:8.2

# Install dependencies
RUN apt-get update -y && apt-get install -y openssl zip unzip git libexif-dev

# Install PHP extensions
RUN docker-php-ext-install pdo exif

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Install dependencies
RUN composer install

# Expose port
EXPOSE 8181

# Run the application
CMD php artisan serve --host=0.0.0.0 --port=8181
